merge con upstream en inglés
hechoendrupal/drupal-console-es pull request #28
Opened 2017-07-24 13:34 UTC by novia713

2017-07-24 17:48 UTC, enzolutions requested changes
Please apply this rule in all files

2017-07-24 17:48 UTC, enzolutions commented on translations/user.create.yml
> +        execution: "drupal user:create  john p455w0rd  \\\n  --roles='authenticated'  \\\n  --email=\"john@anexusit.com\"  \\\n  --status=\"1\""
Hi @novia713 

In order to provide a better output in example section, please don't remove the \ in behalf of \\\n

2017-07-26 19:02 UTC, novia713 commented
@enzolutions con esto debería estar todos los archivos traducidos. revisar por favor.

2017-07-27 02:47 UTC, enzolutions commented
Pero aun esta \\\n en lo de examples, es algo que tienes que ajustar en todos los archivos

2017-07-27 06:54 UTC, novia713 commented
no puede haber ningún `\\n` y tienen que ser todos `\\\n`?
¿es eso lo que falta?

2017-07-27 12:17 UTC, enzolutions commented
Si eso es lo que faltaria, pero esta en todos los archivos :S

2017-07-27 12:44 UTC, novia713 commented
estoy buscando con 
```
leandro at profident in ~/git/drupal-console-es/translations (upd_20170724)
$ grep -E ' \\\\n' *.yml
```
y no encuentro ninguna ocurrencia. son todos `\\\n`
y si suele haber un `\n` al final de cada ejemplo
pero ahora mismo no encuentro ningún `\\n`

¿es posible que estuvieran en el primer commit (un merge)?
después hice 2 commits más ...

si encuentras algún `\\n`, dime dónde ....

2017-07-27 12:49 UTC, enzolutions commented on translations/config.export.single.yml
>          execution: "drupal config:export:single \\\n  --name=config.settings.name \\\n  --remove-uuid \\\n  --remove-config-hash\n"
Creo que no fue en este PR sino en uno pasado, puedes probar que tu example se ve bien cuando corres

drupal [command] --help

2017-07-27 13:16 UTC, novia713 commented
he mirado 4 ó 5 y los veo bien, sale así:
```
Examples:
  Facilitar el nombre de la configuración que será exportada
  drupal config:export:single \
  --name=config.settings.name

  Eliminar el uuid y/o los hashes de configuración en la exportación de la configuración
  drupal config:export:single \
  --name=config.settings.name \
  --remove-uuid \
  --remove-config-hash

Ayuda:
 Exporta configuración como fichero yml.
```

de todos modos, ¿hay alguna manera de previsualizar el libro para ver si se pintan bien los ejemplos sin mergear mi commit en el repo hechodrupal/drupal-console-book?

me gustaría probar el libro en local, pero no se cómo hacerlo @enzolutions

2017-07-28 11:34 UTC, enzolutions commented
Hola @novia713 

Para probar el gitbook, tendrias que hacer un fork y clone local del repositorio https://github.com/hechoendrupal/drupal-console-book

Adicionalmente tendria que tener una copia actualizada del [console-develop](https://github.com/weknowinc/drupal-console-develop) ya sea en modoe dev o desde composer.

Para ejecutar la generacion del capitulo de commands, aqui puedes ver el chain que yo uso para hacerlo
```
  - command: settings:set
    arguments:
      name: language
      value: es
  - command: generate:doc:gitbook
    options:
      path: '%{{directory}}/es'
```

Con el nuevo markdown generado, podrias revisar los archivos en el folder *es/commands* y previsualizar el markdown en tu local a ver como se ve.

Si tienes alguna duda no dudes en contactarme.

2017-07-28 15:55 UTC, novia713 commented
acabo de generar todo el pdf del libro en español en mi sistema con el código de este PR y creo que está bien mergearlo, @enzolutions 
se ve bastante bien :-)
[drupal-console-book_es.pdf](https://github.com/hechoendrupal/drupal-console-es/files/1183574/drupal-console-book_es.pdf)

2017-07-28 21:37 UTC, enzolutions commented
Gracias @novia713

2017-07-28 21:37 UTC, merged